server:
  port: 8089
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/government-agency-api
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect