server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/government-agency-api?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
